(def-fun (power x n) (if (= n 0) 1 (* x (power x (- n 1)))))
(define z (+ 1 2))
(print (power (get-int) 3))
(define y (get-int))
(print (power y 5))
(print (power z 2))
(if (> 3 2) (+ 1234 (get-int)) 5)
(if (< 3 2) (* 100 2) 5)
